import React, { useState } from "react";
import { Upload, Download, File, X, Check, AlertTriangle } from "lucide-react";
import Modal from "../../common/Modal";

const CabangImportExport = ({
  onImport,
  onExport,
  cabangList = [],
  isOpen,
  onClose,
}) => {
  const [activeTab, setActiveTab] = useState("export");
  const [isProcessing, setIsProcessing] = useState(false);
  const [importFile, setImportFile] = useState(null);
  const [importPreview, setImportPreview] = useState(null);
  const [exportFormat, setExportFormat] = useState("csv");
  const [includeFields, setIncludeFields] = useState({
    namaCabang: true,
    alamat: true,
    telepon: true,
    email: true,
    kota: true,
    provinsi: true,
    kodePos: true,
    latitude: true,
    longitude: true,
    radiusGeofence: true,
    status: true,
    jamOperasional: false,
    pengaturanPajak: false,
  });
  const [errors, setErrors] = useState([]);
  const [success, setSuccess] = useState(null);

  // Handle file input change
  const handleFileChange = (e) => {
    const file = e.target.files[0];
    if (!file) return;

    setImportFile(file);
    setErrors([]);
    setSuccess(null);

    // Check file type
    const fileExt = file.name.split(".").pop().toLowerCase();
    if (!["csv", "xlsx", "xls"].includes(fileExt)) {
      setErrors(["Format file tidak didukung. Gunakan CSV atau Excel."]);
      return;
    }

    // Preview would normally be generated by parsing the file
    // This is just a placeholder implementation
    setIsProcessing(true);
    setTimeout(() => {
      // Mock preview data
      const mockPreview = {
        headers: [
          "namaCabang",
          "alamat",
          "telepon",
          "email",
          "kota",
          "provinsi",
          "status",
        ],
        totalRows: 5,
        samples: [
          {
            namaCabang: "Cabang Contoh 1",
            alamat: "Jl. Contoh No. 123",
            telepon: "021-555555",
            email: "cabang1@example.com",
            kota: "Jakarta",
            provinsi: "DKI Jakarta",
            status: "aktif",
          },
          {
            namaCabang: "Cabang Contoh 2",
            alamat: "Jl. Contoh No. 456",
            telepon: "021-666666",
            email: "cabang2@example.com",
            kota: "Bandung",
            provinsi: "Jawa Barat",
            status: "aktif",
          },
        ],
        missingFields: ["kodePos", "latitude", "longitude"],
      };
      setImportPreview(mockPreview);
      setIsProcessing(false);

      // Example validation
      const validationErrors = [];
      if (!mockPreview.headers.includes("namaCabang")) {
        validationErrors.push("Kolom 'namaCabang' wajib ada dalam file");
      }
      if (mockPreview.missingFields.includes("kodePos")) {
        validationErrors.push(
          "Kolom 'kodePos' tidak ditemukan namun dapat diabaikan"
        );
      }
      setErrors(validationErrors);
    }, 1000);
  };

  // Handle include fields change
  const handleIncludeFieldChange = (field) => {
    setIncludeFields((prev) => ({
      ...prev,
      [field]: !prev[field],
    }));
  };

  // Handle export
  const handleExport = () => {
    setIsProcessing(true);

    // Get fields to include
    const fields = Object.entries(includeFields)
      .filter(([_, include]) => include)
      .map(([field]) => field);

    // Call parent export function
    onExport && onExport({ format: exportFormat, fields });

    // Show success message after a delay (simulating processing)
    setTimeout(() => {
      setSuccess(
        `Data cabang berhasil diekspor ke format ${exportFormat.toUpperCase()}`
      );
      setIsProcessing(false);
    }, 1500);
  };

  // Handle import
  const handleImport = () => {
    if (!importFile) return;

    setIsProcessing(true);
    setErrors([]);
    setSuccess(null);

    // Call parent import function
    setTimeout(() => {
      onImport && onImport(importFile, importPreview);
      setSuccess("Data cabang berhasil diimpor");
      setIsProcessing(false);
    }, 2000);
  };

  // Get export filename
  const getExportFilename = () => {
    const date = new Date().toISOString().split("T")[0];
    return `daftar_cabang_${date}.${exportFormat}`;
  };

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title="Impor/Ekspor Data Cabang"
      size="lg"
    >
      <div className="p-6">
        {/* Tabs */}
        <div className="flex border-b mb-6">
          <button
            className={`px-4 py-2 font-medium text-sm border-b-2 -mb-px ${
              activeTab === "export"
                ? "border-indigo-500 text-indigo-600"
                : "border-transparent text-gray-500 hover:text-gray-700"
            }`}
            onClick={() => {
              setActiveTab("export");
              setErrors([]);
              setSuccess(null);
            }}
          >
            <Download className="h-4 w-4 inline-block mr-2" />
            Ekspor Data
          </button>
          <button
            className={`px-4 py-2 font-medium text-sm border-b-2 -mb-px ${
              activeTab === "import"
                ? "border-indigo-500 text-indigo-600"
                : "border-transparent text-gray-500 hover:text-gray-700"
            }`}
            onClick={() => {
              setActiveTab("import");
              setErrors([]);
              setSuccess(null);
              setImportFile(null);
              setImportPreview(null);
            }}
          >
            <Upload className="h-4 w-4 inline-block mr-2" />
            Impor Data
          </button>
        </div>

        {/* Success Message */}
        {success && (
          <div className="mb-4 p-3 bg-green-50 border border-green-200 text-green-700 rounded-md flex items-start">
            <Check className="h-5 w-5 text-green-500 mr-2 flex-shrink-0 mt-0.5" />
            <div>{success}</div>
          </div>
        )}

        {/* Error Messages */}
        {errors.length > 0 && (
          <div className="mb-4 p-3 bg-yellow-50 border border-yellow-200 text-yellow-700 rounded-md flex items-start">
            <AlertTriangle className="h-5 w-5 text-yellow-500 mr-2 flex-shrink-0 mt-0.5" />
            <div>
              <p className="font-medium">Perhatian:</p>
              <ul className="mt-1 ml-5 list-disc text-sm">
                {errors.map((error, index) => (
                  <li key={index}>{error}</li>
                ))}
              </ul>
            </div>
          </div>
        )}

        {/* Export Tab */}
        {activeTab === "export" && (
          <div>
            <div className="mb-4">
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Format File
              </label>
              <div className="flex space-x-4">
                <label className="inline-flex items-center">
                  <input
                    type="radio"
                    name="format"
                    value="csv"
                    checked={exportFormat === "csv"}
                    onChange={() => setExportFormat("csv")}
                    className="h-4 w-4 text-indigo-600 border-gray-300 focus:ring-indigo-500"
                  />
                  <span className="ml-2 text-sm text-gray-700">CSV</span>
                </label>
                <label className="inline-flex items-center">
                  <input
                    type="radio"
                    name="format"
                    value="xlsx"
                    checked={exportFormat === "xlsx"}
                    onChange={() => setExportFormat("xlsx")}
                    className="h-4 w-4 text-indigo-600 border-gray-300 focus:ring-indigo-500"
                  />
                  <span className="ml-2 text-sm text-gray-700">
                    Excel (XLSX)
                  </span>
                </label>
              </div>
            </div>

            <div className="mb-6">
              <label className="block text-sm font-medium text-gray-700 mb-3">
                Pilih Kolom yang Akan Diekspor
              </label>

              <div className="bg-gray-50 p-3 rounded-md border max-h-64 overflow-y-auto">
                <div className="grid grid-cols-2 gap-3">
                  {Object.entries(includeFields).map(([field, include]) => {
                    // Map field names to display names
                    const displayName = {
                      namaCabang: "Nama Cabang",
                      alamat: "Alamat",
                      telepon: "Telepon",
                      email: "Email",
                      kota: "Kota",
                      provinsi: "Provinsi",
                      kodePos: "Kode Pos",
                      latitude: "Latitude",
                      longitude: "Longitude",
                      radiusGeofence: "Radius Geofence",
                      status: "Status",
                      jamOperasional: "Jam Operasional",
                      pengaturanPajak: "Pengaturan Pajak",
                    }[field];

                    return (
                      <div key={field} className="flex items-center">
                        <input
                          id={`field-${field}`}
                          type="checkbox"
                          checked={include}
                          onChange={() => handleIncludeFieldChange(field)}
                          className="h-4 w-4 text-indigo-600 border-gray-300 rounded focus:ring-indigo-500"
                          disabled={field === "namaCabang"} // Nama cabang selalu diinclude
                        />
                        <label
                          htmlFor={`field-${field}`}
                          className={`ml-2 text-sm ${
                            field === "namaCabang" ? "font-semibold" : ""
                          }`}
                        >
                          {displayName}
                          {field === "namaCabang" && (
                            <span className="text-xs text-red-500 ml-1">
                              (wajib)
                            </span>
                          )}
                        </label>
                      </div>
                    );
                  })}
                </div>
              </div>
            </div>

            <div className="text-sm text-gray-500 mb-6">
              <p className="mb-1">
                <span className="font-medium">
                  Total cabang yang akan diekspor:
                </span>{" "}
                {cabangList.length} cabang
              </p>
              <p>
                <span className="font-medium">Nama file:</span>{" "}
                {getExportFilename()}
              </p>
            </div>

            <div className="flex justify-end">
              <button
                type="button"
                onClick={onClose}
                className="px-4 py-2 border rounded-lg text-gray-700 hover:bg-gray-100 mr-2"
              >
                Batal
              </button>
              <button
                type="button"
                onClick={handleExport}
                disabled={isProcessing}
                className={`px-4 py-2 rounded-lg flex items-center ${
                  isProcessing
                    ? "bg-gray-400 cursor-not-allowed"
                    : "bg-indigo-600 hover:bg-indigo-700"
                } text-white`}
              >
                {isProcessing ? (
                  <>
                    <svg
                      className="animate-spin h-4 w-4 text-white mr-2"
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                    >
                      <circle
                        className="opacity-25"
                        cx="12"
                        cy="12"
                        r="10"
                        stroke="currentColor"
                        strokeWidth="4"
                      ></circle>
                      <path
                        className="opacity-75"
                        fill="currentColor"
                        d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                      ></path>
                    </svg>
                    Memproses...
                  </>
                ) : (
                  <>
                    <Download className="h-4 w-4 mr-2" />
                    Ekspor Data
                  </>
                )}
              </button>
            </div>
          </div>
        )}

        {/* Import Tab */}
        {activeTab === "import" && (
          <div>
            <div className="mb-6">
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Unggah File
              </label>
              <div
                className={`border-2 border-dashed rounded-lg p-6 text-center relative ${
                  importFile
                    ? "border-indigo-300 bg-indigo-50"
                    : "border-gray-300"
                }`}
              >
                {importFile ? (
                  <div className="flex items-center justify-center">
                    <File className="h-8 w-8 text-indigo-500 mr-3" />
                    <div className="text-left">
                      <p className="text-sm font-medium text-gray-900">
                        {importFile.name}
                      </p>
                      <p className="text-xs text-gray-500">
                        {(importFile.size / 1024).toFixed(2)} KB
                      </p>
                    </div>
                    <button
                      onClick={() => {
                        setImportFile(null);
                        setImportPreview(null);
                        setErrors([]);
                      }}
                      className="ml-3 p-1 text-gray-400 hover:text-gray-500 rounded-full hover:bg-gray-100"
                    >
                      <X className="h-5 w-5" />
                    </button>
                  </div>
                ) : (
                  <div>
                    <Upload className="h-10 w-10 text-gray-400 mx-auto mb-2" />
                    <p className="text-gray-600">
                      Klik atau seret file CSV/Excel ke area ini
                    </p>
                    <p className="text-xs text-gray-500 mt-1">
                      Format yang didukung: CSV, XLSX, XLS (maksimal 5MB)
                    </p>
                  </div>
                )}
                <input
                  type="file"
                  accept=".csv,.xlsx,.xls"
                  onChange={handleFileChange}
                  className={`absolute inset-0 w-full h-full opacity-0 cursor-pointer ${
                    importFile ? "pointer-events-none" : ""
                  }`}
                />
              </div>
            </div>

            {isProcessing && (
              <div className="flex flex-col items-center justify-center py-4">
                <div className="animate-spin rounded-full h-10 w-10 border-t-2 border-b-2 border-indigo-500 mb-3"></div>
                <p className="text-gray-600">Memproses file...</p>
              </div>
            )}

            {importPreview && (
              <div className="mb-6">
                <h3 className="text-sm font-medium text-gray-700 mb-3">
                  Preview Data ({importPreview.totalRows} baris)
                </h3>
                <div className="overflow-x-auto border rounded-lg">
                  <table className="min-w-full divide-y divide-gray-200">
                    <thead className="bg-gray-50">
                      <tr>
                        {importPreview.headers.map((header) => (
                          <th
                            key={header}
                            className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                          >
                            {header}
                          </th>
                        ))}
                      </tr>
                    </thead>
                    <tbody className="bg-white divide-y divide-gray-200">
                      {importPreview.samples.map((row, index) => (
                        <tr key={index}>
                          {importPreview.headers.map((header) => (
                            <td
                              key={header}
                              className="px-4 py-3 whitespace-nowrap text-sm"
                            >
                              {row[header] || "-"}
                            </td>
                          ))}
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
                <p className="text-xs text-gray-500 mt-2">
                  * Hanya menampilkan {importPreview.samples.length} baris
                  pertama sebagai preview
                </p>
              </div>
            )}

            <div className="flex justify-end">
              <button
                type="button"
                onClick={onClose}
                className="px-4 py-2 border rounded-lg text-gray-700 hover:bg-gray-100 mr-2"
              >
                Batal
              </button>
              <button
                type="button"
                disabled={
                  !importFile ||
                  isProcessing ||
                  errors.some((e) => e.includes("wajib"))
                }
                onClick={handleImport}
                className={`px-4 py-2 rounded-lg flex items-center ${
                  !importFile ||
                  isProcessing ||
                  errors.some((e) => e.includes("wajib"))
                    ? "bg-gray-400 cursor-not-allowed"
                    : "bg-indigo-600 hover:bg-indigo-700"
                } text-white`}
              >
                {isProcessing ? (
                  <>
                    <svg
                      className="animate-spin h-4 w-4 text-white mr-2"
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                    >
                      <circle
                        className="opacity-25"
                        cx="12"
                        cy="12"
                        r="10"
                        stroke="currentColor"
                        strokeWidth="4"
                      ></circle>
                      <path
                        className="opacity-75"
                        fill="currentColor"
                        d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                      ></path>
                    </svg>
                    Memproses...
                  </>
                ) : (
                  <>
                    <Upload className="h-4 w-4 mr-2" />
                    Impor Data
                  </>
                )}
              </button>
            </div>
          </div>
        )}
      </div>
    </Modal>
  );
};

export default CabangImportExport;
